# Generated by Django 5.0.3 on 2024-03-29 18:09

import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicalProfessional',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('medical_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('General Physician', 'General Physician'), ('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist')], max_length=100, null=True)),
                ('education_and_qualifications', models.TextField(blank=True, null=True)),
                ('work_history', models.TextField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('clinic_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('department_or_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic_schedule', models.TextField(blank=True, null=True)),
                ('patient_load', models.IntegerField(default=0)),
                ('messaging_system', models.BooleanField(default=True)),
                ('appointment_scheduling', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], max_length=50, null=True)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.medicalprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('genotype', models.CharField(blank=True, max_length=50, null=True)),
                ('smoking_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('alcohol_consumption', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('bmi', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.TextField()),
                ('preferred_pharmacy', models.TextField()),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Yoruba', 'Yoruba'), ('Igbo', 'Igbo'), ('Hausa', 'Hausa')], default='English', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('medical_conditions', models.TextField()),
                ('allergies', models.TextField()),
                ('medications', models.TextField()),
                ('immunization_history', models.TextField()),
                ('family_medical_history', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('reason_for_visit', models.TextField()),
                ('treatments_received', models.TextField()),
                ('physician_notes', models.TextField()),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='users.medicalprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('blood_tests', models.TextField()),
                ('imaging_studies', models.TextField()),
                ('electrocardiogram', models.TextField()),
                ('other_tests', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('visit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.visithistory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalUpload',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(max_length=500, upload_to=users.utils.medical_upload_file_name)),
                ('visit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.visithistory')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
