# Generated by Django 5.0.3 on 2024-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_birthday_user_date_of_birth_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='preferred_pharmacy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
