# Generated by Django 5.0.3 on 2024-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patient_preferred_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'Ab'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'Aa'), ('AB', 'Ab'), ('BB', 'Bb'), ('AO', 'Ao'), ('BO', 'Bo'), ('OO', 'Oo'), ('SS', 'Ss'), ('AS', 'As'), ('SC', 'Sc'), ('CC', 'Cc'), ('AC', 'Ac')], max_length=2, null=True),
        ),
    ]
