# Generated by Django 5.0.3 on 2024-03-29 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patient_bmi_alter_patient_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalprofessional',
            old_name='department_or_unit',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='appointment_scheduling',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='clinic_affiliation',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='clinic_schedule',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='messaging_system',
        ),
        migrations.RemoveField(
            model_name='medicalprofessional',
            name='patient_load',
        ),
    ]
