# Generated by Django 5.0.3 on 2024-05-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_address_user_address_1_user_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
