# Generated by Django 5.0.3 on 2024-06-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_patient_emergency_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
