# Generated by Django 5.0.3 on 2024-06-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='medicalprofessional',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General Physician', 'General Physician'), ('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Ophthalmologist', 'Ophthamologist')], max_length=100, null=True),
        ),
    ]
