# Generated by Django 5.0.3 on 2024-06-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_medicalhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='family_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='immunization_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
