# Generated by Django 5.0.3 on 2024-06-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_medicalhistory_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
