# Generated by Django 5.0.3 on 2024-07-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='visit_history',
        ),
        migrations.RemoveField(
            model_name='visithistory',
            name='medical_professional',
        ),
        migrations.RemoveField(
            model_name='visithistory',
            name='patient',
        ),
        migrations.DeleteModel(
            name='MedicalUpload',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
