# Generated by Django 5.0.3 on 2024-06-16 13:18

import django.db.models.deletion
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_delete_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Active', 'Active'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.medicalprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.medicalprofessional')),
            ],
        ),
    ]
