# Generated by Django 5.0.3 on 2024-07-08 18:13

import django.db.models.deletion
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_availability_options'),
        ('users', '0015_remove_testresult_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('reason_for_visit', models.TextField()),
                ('treatments_received', models.TextField()),
                ('physician_notes', models.TextField()),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('medical_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='users.medicalprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('blood_tests', models.TextField()),
                ('imaging_studies', models.TextField()),
                ('electrocardiogram', models.TextField()),
                ('other_tests', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('visit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.visithistory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalUpload',
            fields=[
                ('id', models.UUIDField(default=users.utils.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(max_length=500, upload_to=users.utils.medical_upload_file_name)),
                ('visit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='appointments.visithistory')),
            ],
        ),
    ]
