# Generated by Django 5.0.3 on 2024-07-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_visithistory_testresult_medicalupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
