# Generated by Django 5.0.3 on 2024-07-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_visithistory_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithistory',
            name='physician_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='treatments_received',
            field=models.TextField(blank=True, null=True),
        ),
    ]
